version: '3'
services:
  nginx:
    image: mjspk/cms_nginx:latest
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  api:
    image: mjspk/cms_api:latest
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
  client:
    image: mjspk/cms_client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
